### ISSUE TITLE
Successive calls get slower and slower

### ISSUE THREAD

**Issue by CutmanCometh** [ashupp/js-image-generator#1]
Successive calls to generateImage keep getting slower, up to a max of about 7 seconds per call.

The following code:

`let now = Date.now();`
`for(var i = 0;  i < 1000; i++){`
`imgGen.generateImage(2000,2000,80, function(err, image){`
`console.log(i, (now - (now = Date.now())) * -1 + ' ms');//calculate and reassign both at once`
`});`
`}`

Results in the following output:

0 '1024 ms'
1 '1060 ms'
2 '1079 ms'
3 '1045 ms'
4 '1089 ms'
5 '1051 ms'
6 '1122 ms'
7 '1142 ms'
8 '1900 ms'
9 '1919 ms'
10 '1943 ms'
11 '2016 ms'
12 '2043 ms'
13 '2057 ms'
14 '2712 ms'
15 '3323 ms'
16 '5265 ms'
17 '5340 ms'
18 '7192 ms'
19 '7220 ms'
20 '7184 ms'

It stays at around 7.2 seconds after that.

If I have some time, I'll clone your code and see if I can figure out what's going on.

(PS: Thanks for creating this module)

**Comment by ashupp** [comment]
Hello and thanks for your comment

I just did a quick run with manual garbage collection and added a `global.gc();` to the loop.
`"node --expose-gc test.js"`

I got the following result:

0 '988 ms'
1 '1045 ms'
2 '1078 ms'
3 '1073 ms'
4 '1056 ms'
5 '1068 ms'
6 '1058 ms'
7 '1064 ms'
8 '1075 ms'
9 '1207 ms'
10 '1239 ms'
11 '4212 ms'
12 '1053 ms'
13 '1058 ms'
14 '1059 ms'
15 '1059 ms'
16 '1067 ms'
17 '1060 ms'
18 '1057 ms'
19 '1058 ms'
20 '1138 ms'

as you can see its rising and dropping again.
Seems to me like a memory problem / leak?
Don´t know right now if the problem is in my code or the underlying jpeg-js library.

Anyway - maybe this workaround speeds up your image generation process :)

Best regards

**Comment by ashupp** [comment]
Problem seems solved with version 1.0.3 and jpeg-js 0.4.2
